### ISSUE TITLE
RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Microsoft/singleshotpose#10]
Hi,

Running the following on Ubuntu 16.04.:  

`python train.py cfg/ape.data cfg/yolo-pose.cfg backup/ape/init.weights`

results with:

`RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3`

For which the solution is editing the line 175 in cfg.py to:

`conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w]).view(conv_model.weight.data.shape)); start = start + num_w`

**Comment by hhaAndroid** [comment]
You should use Pytorch 0.3，dont use Pytorch0.4

**Comment by eyildiz-ugoe** [comment]
Fair enough, just in case if someone gets the same error. Closing the issue.
