### ISSUE TITLE
What is the role of VOC2012？

### ISSUE THREAD

**Issue by MrLuer** [microsoft/singleshotpose#117]
I notice that ，there is code in train.py : 
bg_file_names = get_all_files('VOCdevkit/VOC2012/JPEGImages')
train_loader = torch.utils.data.DataLoader(bg_file_names=bg_file_names。。。。。)

I wonder what is the role of voc2012 when training my own dataset

**Comment by AkmaralMoldagalieva** [comment]
hi!

They are used for data augmentation, used to replace the background of an object of interest. In case you put False for data augmentation, they are not used, you can ignore.

**Comment by MrLuer** [comment]
ok，thank you
