### ISSUE TITLE
How can i get the 3D bounding box

### ISSUE THREAD

**Issue by jhellzhang** [microsoft/singleshotpose#119]
How can i get the 3D bounding box surrounding the 3D object model,and which tools is chosen?

**Comment by jhellzhang** [comment]
> How can i get the 3D bounding box surrounding the 3D object model,and which tools is chosen?



> How can i get the 3D bounding box surrounding the 3D object model,and which tools is chosen?



> How can i get the 3D bounding box surrounding the 3D object model,and which tools is chosen?

**Comment by capslocknanda** [comment]
how do you solve that?
