### ISSUE TITLE
What is the "diam" parameter in the datafiles?

### ISSUE THREAD

**Issue by Pai-Sho** [Microsoft/singleshotpose#13]
I understand this is probably the model diameter for purposes of 6D pose estimation metric, but what are the units? Is it scaled somehow? Is it the diameter along a particular axis?

**Comment by btekin** [comment]
Here the diameter refers to the maximum distance among the distances between each vertex of the 3D object model. Its unit is given in meters.

**Comment by Pai-Sho** [comment]
Thank you! I'm assuming this is found with the modeling software you used to create the models?

**Comment by PeterZheFu** [comment]
@btekin thanks for your work. May I know why the diameter value is involved? Thank you.

**Comment by btekin** [comment]
We need the diameter value when evaluating the accuracy. When computing the accuracy of our approach on the LineMod dataset with the so called ADD metric, we take a pose estimate to be correct if the mean distance between the true coordinates of 3D mesh vertices and those estimated given the pose is less than 10% of the object’s diameter.
