### ISSUE TITLE
visualization problem

### ISSUE THREAD

**Issue by JiangDing1995** [Microsoft/singleshotpose#130]
@btekin Hi, when i want to run valid.ipynb in Jupter Notebook for a single object visualization(such as ape), here is the error:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-9d922bd741c6> in <module>()
    244 modelcfg   = 'C:/chengxu/singleshotpose-master/cfg/yolo-pose.cfg'
    245 weightfile = 'C:/chengxu/singleshotpose-master/backup/ape/model_backup.weights'
--> 246 valid(datacfg, modelcfg, weightfile)
    247 

<ipython-input-4-9d922bd741c6> in valid(datacfg, modelcfg, weightfile)
     52 
     53     # Read object model information, get 3D bounding box corners
---> 54     mesh      = MeshPly(meshname)
     55     vertices  = np.c_[np.array(mesh.vertices), np.ones((len(mesh.vertices), 1))].transpose()
     56     corners3D = get_3D_corners(vertices)

~\MeshPly.py in __init__(self, filename, color)
      4     def __init__(self, filename, color=[0., 0., 0.]):
      5 
----> 6         f = open(filename, 'r')
      7         self.vertices = []
      8         self.colors = []

FileNotFoundError: [Errno 2] No such file or directory: 'LINEMOD/ape/ape.ply'

Obviously there is "ape.ply" in the folder"LINEMOD/ape",why still can't find it? 
i have installed "plyfile",but it doesn't work. Anyone help?

**Comment by banannakn** [comment]
There must be a problem with the data path. You can try check this out, with the full root path of the ply-model, whether this is working.

**Comment by JiangDing1995** [comment]
Thanks for your reply. I have tried this (at the bottom of MeshPly.py):
if __name__ == '__main__':
    path_model = 'C:/chengxu/singleshotpose-master/LINEMOD/ape/ape.ply'           #(here)
    mesh = MeshPly(path_model)

but it seems failed again,the same error. I don't know whether it is the right place to add. Or where do i need to put(or modify) the full path of the ply-model?.......
I have not seen anybody meeting this problem yet.

**Comment by banannakn** [comment]
you can edit the ply-path in the cfg-folder for one specific object in the data-file for that object

**Comment by JiangDing1995** [comment]
Thanks! I have modified the path in "ape.data" all:

train  = C:/chengxu/singleshotpose-master/LINEMOD/ape/train.txt
valid  = C:/chengxu/singleshotpose-master/LINEMOD/ape/test.txt
backup = C:/chengxu/singleshotpose-master/backup/ape
mesh = C:/chengxu/singleshotpose-master/LINEMOD/ape/ape.ply
tr_range = C:/chengxu/singleshotpose-master/LINEMOD/ape/training_range.txt

but when i run the .ipynb file, another error appeared:
NameError                                 Traceback (most recent call last)
<ipython-input-3-2ae9890bcf97> in <module>()
    244 modelcfg   = 'C:/chengxu/singleshotpose-master/cfg/yolo-pose.cfg'
    245 weightfile = 'C:/chengxu/singleshotpose-master/backup/ape/model.weights'
--> 246 valid(datacfg, modelcfg, weightfile)
    247 

<ipython-input-3-2ae9890bcf97> in valid(datacfg, modelcfg, weightfile)
      6 
      7     # Parse configuration files
----> 8     data_options = read_data_cfg(datacfg)
      9     valid_images = data_options['valid']
     10     meshname     = data_options['mesh']

NameError: name 'read_data_cfg' is not defined

however,  'read_data_cfg' actually exists in "utils.py" file, very strange......

**Comment by JiangDing1995** [comment]
Sorry, i closed the file and open it again, now it works. thank you very much
