### ISSUE TITLE
Bug: when pixels on the mask's borders are non-zero?

### ISSUE THREAD

**Issue by tobycollins** [Microsoft/singleshotpose#134]
There seems to be a bug when the borders of the mask image have non-zero values. This can occur when the object is partially in frame. an error is thrown:

File "region_loss.py", line 40, in build_targets
    conf_mask[b][cur_confs>sil_thresh] = 0
RuntimeError: The shape of the mask [169] at index 0 does not match the shape of the indexed tensor [1, 13, 13] at index 0

If I manually set the borders of the mask image to be zero, the problem disappears. It is probably something to do with the composition of the mask with random background images.

**Comment by linkq-goldeneye** [comment]
hi, @tobycollins ,
What  background images are you using?
