### ISSUE TITLE
some questions about the paper 

### ISSUE THREAD

**Issue by edisonchensy** [Microsoft/singleshotpose#14]
Hi, Mr. Tekin

I am reading your paper(Real-time Seamless Single Shot 6D Object Prediction) and I have some questions. This is my first time dealing with object pose estimation problem. In your paper, you mentioned 9 control points, but YOLO can only regress 2D bounding box of the objects and its class. Previously, I was working on SSD, I am not very familiar with YOLO, but I think YOLO and SSD are similar. Here are the questions:

1) How to predict the projections of the 3D bounding box corners in the image by using YOLO? Since YOLO can only regress 2D bounding box(object's location in the image) of the objects and its class.
 
2) You selected 9 control points(8 points are the corners, 1 point is the center). How do you get these 9 points?  and the 3D ground truth points?

3) What data is known? For example, the dimension of objects?  the depth? the camera intrinsic? the point cloud data?

**Comment by btekin** [comment]
Here are the answers to your questions: 

1. We modify the loss function of YOLO such that we do not predict the 2D bounding box, but the projections of the 9 control points in the 3D object model. Please see Section 3.1 of the paper for further details.

2. The ground-truth 3D model of the object is provided in the dataset. 8 corners of the 3D object model are basically [[min_x, min_y, min_z], [min_x, min_y, max_z], [min_x, max_y, min_z], [min_x, max_y, max_z], [max_x, min_y, min_z], [max_x, min_y, max_z], [max_x, max_y, min_z], [max_x, max_y, max_z]] positions of the 3D object model.

3. Here, in this model based 6D pose estimation problem, 3D object model and the camera intrinsic is assumed to be known. In our case, we do not assume to know the full detailed 3D model of the object as in previous studies but just a rough framing of the object (3D bounding box). The depth of the object is not assumed to be known but rather it is estimated (z-component of the translation vector).

P.S. As this is not an issue for the code, but rather general questions about the paper, maybe it's better to discuss about these on email.

**Comment by edisonchensy** [comment]
i get it, thank you very much
