### ISSUE TITLE
RuntimeError: The size of tensor a (13) must match the size of tensor b (169) at non-singleton dimension 2

### ISSUE THREAD

**Issue by LEEHK96** [Microsoft/singleshotpose#145]
File "C:\Libs\Pycham\singleshotpose\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\seongheum\Desktop\kittidataset\region_loss.py", line 135, in forward
    build_targets(pred_corners, target.data, num_keypoints, nA, nC, nH, nW, self.noobject_scale, self.object_scale, self.thresh, self.seen)
  File "C:\Users\seongheum\Desktop\kittidataset\region_loss.py", line 42, in build_targets
    cur_confs  = torch.max(cur_confs, corner_confidences(cur_pred_corners, cur_gt_corners)).view_as(conf_mask[b]) # some irrelevant areas are filtered, in the same grid multiple anchor boxes might exceed the threshold
RuntimeError: The size of tensor a (13) must match the size of tensor b (169) at non-singleton dimension 2

I made the label and image set into the format with the kitti dataset.
 I tried train without mask, but it doesn't work with the following error. 
Do you know anyone? The label's accurate. I checked gt with the matlab

**Comment by julingers** [comment]
hello, can you tell me how did you solve it? Hope for your help.
