### ISSUE TITLE
Problem with training it on Google Colab

### ISSUE THREAD

**Issue by hyoon970** [Microsoft/singleshotpose#152]
Hello,

I'm trying to run this code on Google Colab, but I'm facing the problem below.

RuntimeError: CuDNN error: CUDNN_STATUS_EXECUTION_FAILED

I changed batch size to 8, and tried to change CUDA and CUDNN version as well.

(CUDA 8.0, CUDNN 5.1 failed / CUDA 8.0, CUDNN 7.1.3 failed / CUDA 9.2, CUDNN 7.1.3 failed)

However, it failed.

I think that batch size is not a problem, but version of CUDA and CUDNN would be the reason of problem.

Is here any person who ran this code in Google Colab?

Thanks and Regards,

H. Yoon

**Comment by hyoon970** [comment]
I found the answer. Don't touch CUDA and cudnn(Colab already has them). Just install pytorch 0.4.1

**Comment by CVUsers** [comment]
hello ，What's your environment? I can't successfully train and verify this GitHub. Do you have wechat?

**Comment by hyoon970** [comment]
I don't have wechat. 

I used Google Colab (Jupyter notebook).

If you have same problem above, don't touch CUDA or CUDNN. Just install pytorch.

**Comment by kordou** [comment]
can you tell me how did you run it on colab please ?
