### ISSUE TITLE
Enabling Visual Output

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Microsoft/singleshotpose#16]
Is there a way to produce at least some visual output just like the Figure 3 in the paper:

![1](https://user-images.githubusercontent.com/35396058/42630256-6996d3ea-85d6-11e8-8152-5238e0b2f191.png)

Right now the output is only textual, which is OK but since the paper tackles essentially a "vision" problem, it would be nice to have visual output next to the textual one. 

Or perhaps you could tell a quick hack for us which can enable some visualization? I mean, since you captured the images in the paper, you already have the module somehow in the code, it is just not used I guess. 

P.S: The work looks great, and we would like to actually really invest our time in utilizing it. If you can help people in this regard, I believe you can get a lot of citations in the close future :)

**Comment by btekin** [comment]
We already provide a jupyter notebook (valid.ipynb) which include a small script that visualizes our outputs. Thanks for the feedback :)

**Comment by eyildiz-ugoe** [comment]
Perfect!

**Comment by G-YY** [comment]
> We already provide a jupyter notebook (valid.ipynb) which include a small script that visualizes our outputs. Thanks for the feedback :)
hello btekin, in the multi_obj_pose_estimation folder,why the train list in cfg/train_occlusion.txt has only one object  instead of multi objects?  @btekin thank you
