### ISSUE TITLE
Bad Training Result with the defaults parameters and default dataset 

### ISSUE THREAD

**Issue by AristideLaignel** [Microsoft/singleshotpose#186]
Hi, 

I'm trying to retrain the model with just changing the conversion of the data to the cpu in the region_loss.py but I have bad results in all epochs. I'm using CUDA 11.1, python 3.8, Pytorch 1.8.0 and Cudnn 8.8.1 on Ubuntu 20.04. 
Here, the results I have : 

![image](https://user-images.githubusercontent.com/46279890/226870796-214fc515-54af-4ae2-9525-31a8408c469c.png)

and when I test the model retrain I don't have a good result when I print the 3D bounding boxes :

![1Ape26](https://user-images.githubusercontent.com/46279890/226871367-10fc02c0-e6fe-4260-95e4-1c14c967866c.png)

Here the command like in the example I launch : 

python train.py --datacfg cfg/benchvise.data --modelcfg cfg/yolo-pose.cfg --initweightfile backup/benchvise/init.weights

And it doesn't work with all models 

Is there some parameters to adjust to have good training result ?

Thanks you for your help !!

**Comment by zongt-yu** [comment]
> 
Hello, have you solved it?

**Comment by AristideLaignel** [comment]
Yes, In the region_loss.py at line 153, I change this :

```
loss_x    = np.sum(loss_xs)
loss_y    = np.sum(loss_ys)
```

by this : 

```
stacked_tensor_x = torch.stack(loss_xs, dim=0)
stacked_tensor_y = torch.stack(loss_ys, dim=0)

loss_x = torch.sum(stacked_tensor_x)
loss_y = torch.sum(stacked_tensor_y)
```
