### ISSUE TITLE
Input and output

### ISSUE THREAD

**Issue by zhujiawen1994** [Microsoft/singleshotpose#19]
Hi, sir, I am sorry to bother you, but I have a few simple questions to ask you. From the paper, I learned that the input is a picture or a set of RGB images, and the output is 6D pose (this article uses 21 numbers). I want to ask what should i do to process an RGB image as input, using the network(you have trained model) to get the output(6Dpose of the object)?
Looking forward to your reply!

**Comment by btekin** [comment]
As also explained in the readme file, our output target representation consist of 21 values. We predict 9 control points corresponding to the centroid and corners of the 3D object model. Then, given the 2D predictions and known 3D locations of 9 control points, we apply perspective-n-point (PnP) algorithm to estimate 6D pose of the object in terms of a rotation matrix and the translation vector. 

Additionally we predict the class in each cell. That makes 9x2+1 = 19 points. In multi-object training, during training, we assign whichever anchor box has the most similar size to the current object as the responsible one to predict the 2D coordinates for that object. To encode the size of the objects, we have additional 2 numbers for the range in x dimension and y dimension. Therefore, we have 9x2+1+2 = 21 numbers

**Comment by zhujiawen1994** [comment]
First of all, thank you for your reply!Maybe I didn't express my meaning clearly. I understand the meaning of the readme file, and I followed the steps to experiment, but the output is not the 21 numbers we want, but the percentage of accuracy. To put it directly, I want to ask how I get 21 numbers instead of percentages. And the paper says that the input is an RGB image, but I think the input to the network should not be just a .JPG image, so what do I need to do to meet the network requirements for input on the .jpg image?
Because I read your article, I think that both the starting point and the meaning are very valuable for learning and using. So I actually want to directly use the network you have trained, take the .jpg image as input, and get the 6Dpose of the object. I don't know if I understand the error？
Looking forward to your reply!

**Comment by btekin** [comment]
I see, the 6D pose of the object is basically defined as the rotation matrix and translation vector. The predictions for them correspond to the R_pr and t_pr variables in the valid.py function, if that's what you're asking for. The only input to the network is an RGB image. Additionally, the method uses the reference 3D bounding box of the object model and intrinsic camera matrix to recover the 6D pose of the object.
