### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'LINEMOD/ape/train.txt'

### ISSUE THREAD

**Issue by edisonchensy** [Microsoft/singleshotpose#2]
I have downloaded all the materials required.  When I try to train the model ( python train.py cfg/ape.data cfg/yolo-pose.cfg /data1/edison/realtime_seamless_6D_data_and_model/dataset/backup/ape/init.weights
)
It has error: 

  File "train.py", line 289, in <module>
    nsamples      = file_lines(trainlist)
  File "/home/edison/realtime_seamless_yolo_6D/singleshotpose/utils.py", line 1006, in file_lines
    thefile = open(thefilepath, 'rb')
IOError: [Errno 2] No such file or directory: 'LINEMOD/ape/train.txt'

could you please tell me how to solve this?? Thank you

**Comment by edisonchensy** [comment]
by the way, i can find the train.txt file in /data1/edison/realtime_seamless_6D_data_and_model/dataset/LINEMOD/ape/ , where i saved

**Comment by btekin** [comment]
Did you place the LINEMOD dataset within the main code folder? It seems that your main code is in "home/edison/realtime_seamless_yolo_6D/singleshotpose/" but your data is in "/data1/edison/realtime_seamless_6D_data_and_model/dataset/". If you place the dataset folder within the main code folder, you should be able to run the code without any modifications. But if the dataset is in another folder, you should adjust the paths accordingly, e.g. you should, for example, change the first line in cfg/ape.data file to "/data1/edison/realtime_seamless_6D_data_and_model/dataset/LINEMOD/ape/train.txt", along with the paths of other data files.

**Comment by edisonchensy** [comment]
Thank you very much for your previous help, I have change all the directories for objects in 'cfg' file. by the way , i did not find "phone" file in LINEMOD dataset file you provided.  now i try to train the network again ( python train.py cfg/ape.data cfg/yolo-pose.cfg /data1/edison/realtime_seamless_6D_data_and_model/dataset/backup/ape/init.weights)  it shows the error below, could you please give me a help?

Traceback (most recent call last):
  File "train.py", line 336, in <module>
    model.load_weights_until_last(weightfile)
  File "/home/edison/realtime_seamless_yolo_6D/singleshotpose/darknet.py", line 315, in load_weights_until_last
    start = load_conv_bn(buf, start, model[0], model[1])
  File "/home/edison/realtime_seamless_yolo_6D/singleshotpose/cfg.py", line 175, in load_conv_bn
    conv_model.weight.data.copy_(torch.from_numpy(buf[start:start+num_w])); start = start + num_w
RuntimeError: The expanded size of the tensor (3) must match the existing size (864) at non-singleton dimension 3

**Comment by edisonchensy** [comment]
i have change the image directory in train.py as well. ( bg_file_names = get_all_files('/data1/edison/realtime_seamless_6D_data_and_model/dataset/VOCdevkit/VOC2012/JPEGImages/'))
