### ISSUE TITLE
Multi-Obj Visualization

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Microsoft/singleshotpose#23]
Running `multi-valid.py` with visualization taken from the notebook side results with images that are somehow weird, as seen below:

![output_0_](https://user-images.githubusercontent.com/35396058/42876287-79d9bc04-8a86-11e8-8098-ca1f8dfeb619.png)
![output_1_](https://user-images.githubusercontent.com/35396058/42876288-79f34804-8a86-11e8-9eea-c98dc8b66411.png)
![output_2_](https://user-images.githubusercontent.com/35396058/42876289-7a0c6546-8a86-11e8-8bdb-24afd2f1768b.png)

The code snippets I used are taken from the notebook file (I just save them instead of displaying them):

```
      # Images
        img = data[0, :, :, :]
        img = img.numpy().squeeze()
        img = np.transpose(img, (1, 2, 0))

```

```
# Visualize
                fig = plt.figure()
                plt.xlim((0, 640))
                plt.ylim((0, 480))
                plt.imshow(scipy.misc.imresize(img, (480, 640)))
                # Projections
                for edge in edges_corners:
                    plt.plot(proj_corners_gt[edge, 0], proj_corners_gt[edge, 1], color='g', linewidth=3.0)
                    plt.plot(proj_corners_pr[edge, 0], proj_corners_pr[edge, 1], color='b', linewidth=3.0)
                plt.gca().invert_yaxis()
                #plt.show() 

                plt.savefig(outfile + '/output_' + str(count) + '_.png', bbox_inches='tight')
                fig.canvas.draw()
                count = count + 1
```

Is there a way to visualize the multi-object setup as it is seen in the paper supplement?

**Comment by btekin** [comment]
For multi-object scenario, detection is not always very accurate, but here you show **only** the failure cases. When the corner points are not so accurate, pnp results in unreliable estimates. We provide results for individual pose estimates separately, visualizing multiple of them is just a matter of augmenting them in the same image.

**Comment by eyildiz-ugoe** [comment]
Oh okay, I thought I made a mistake regarding the visualization. Alright then, PnP fails due to the inaccurate corner points, that's why I get these results. Thanks for the clarification.

**Comment by Rajat-Mehta** [comment]
@eyildiz-ugoe I get similar plots as yours. What is the reason for this and how to solve this issue? thanks in advance.
