### ISSUE TITLE
Issue 24 Reopened: Preprocessing LINEMOD Dataset Query

### ISSUE THREAD

**Issue by sangramioi** [Microsoft/singleshotpose#27]
Hey @btekin ,

Apologies for missing out on your quick response on the Issue, I had some queries on the same but the issue was closed by you so I took the liberty of opening a new issue with the same name, hope you don't mind.
---------------------------------------------------------------
Just for confirmation, the fwd projection in part 2 of my question is clear but the position of those fwd projected points in 2D images is after we have the mask, right? Since, the exact coordinates of the center object in the dataset are not given and the **images are not centered on the object.** 

_In short, in 2_. The labels are forward projection of 3D bounding box but the way we obtain their local coordinates on 2D image(not w.r.t to each other) since the images are not object centered is still confusing. 

Say this is my mesh : 

![snapshot_ape00](https://user-images.githubusercontent.com/4083183/43333791-b942a80a-91cb-11e8-9aa6-866b321bcbe7.png)

This is my fwd projection of 3D coordinates into two 2D(_I have the 8 2D coordinates too_):

![0001](https://user-images.githubusercontent.com/4083183/43333869-f8301070-91cb-11e8-9fdd-76e1b916e2dc.png)

**But how does this help on my training image label(8 coordinates in this following image) which is this, where I am not aware which part of the image is the ape object actually in**

![000064](https://user-images.githubusercontent.com/4083183/43334037-7c2bd8e6-91cc-11e8-9a74-bd1208235426.jpg)

**Comment by btekin** [comment]
Sure, no problem, I thought you didn't have any further questions, but you could also reopen the old one. How do you get the second image? The projection doesn't seem to be correct, The projection image should not necessarily be centered on the object. Do you use the `compute_projection` function in `utils.py` and do you use the object models that we provide? Can you try with `compute_projection` function and let me know?

**Comment by sangramioi** [comment]
Yes, there was a mistake in my testing code. It works as you describe. Thank you for your help :)
