### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/cvlabdata1/home/btekin/ope/yolo6D/LINEMOD/benchvise/JPEGImages/001129.jpg'

### ISSUE THREAD

**Issue by nkalavak** [Microsoft/singleshotpose#29]
I am trying to run the multi-object pose estimation script. I noticed the error I got in multiple solved issues. The solution proposed was to download the latest version of the scripts. However, that did not help my case. 

```
Traceback (most recent call last):
  File "train_multi.py", line 408, in <module>
    niter = train(epoch)
  File "train_multi.py", line 72, in train
    for batch_idx, (data, target) in enumerate(train_loader):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IOError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/sspe/singleshotpose/multi_obj_pose_estimation/dataset_multi.py", line 68, in __getitem__
    img, label = load_data_detection(imgpath, self.shape, jitter, hue, saturation, exposure, bgpath)
  File "/sspe/singleshotpose/multi_obj_pose_estimation/image_multi.py", line 446, in load_data_detection
    total_masked_img, label, total_mask = augment_objects(imgpath, objname, add_objs, shape, jitter, hue, saturation, exposure)
  File "/sspe/singleshotpose/multi_obj_pose_estimation/image_multi.py", line 376, in augment_objects
    img = Image.open(imgpath).convert('RGB')
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/cvlabdata1/home/btekin/ope/yolo6D/LINEMOD/benchvise/JPEGImages/001129.jpg'
```

I have placed the files in the recommended method. It looks like this:
```
I have no name!@db80008d79f2:/sspe/singleshotpose$ ls
LICENSE      MeshPly.py   VOCtrainval_11-May-2012.tar  cfg.py	   gdown.pl		      train.py	   valid.py
LICENSE.txt  MeshPly.pyc  backup		       cfg.pyc	   image.py		      utils.py
LINEMOD      README.md	  backup.tar		       darknet.py  multi_obj_pose_estimation  utils.pyc
LINEMOD.tar  VOCdevkit	  cfg			       dataset.py  region_loss.py	      valid.ipynb
```
Any idea what else could be causing this issue? Thanks in advance.

**Comment by snsinha** [comment]
Hi Niveditha,
the error message on the last line seems to indicate that the dataset path is still pointing to the old one '/cvlabdata1/home/btekin/...'. Please check the README file for instructions on how to update the dataset path once you have downloaded the code.
Sudipta

**Comment by nkalavak** [comment]
Hello Sudipta,

Could you point to where the dataset path is set? I downloaded the files mentioned (LINEMOD) after I am in the GitHub repo, as suggested in the README. The output of files present inside the folder is shown to the bottom of my issue. However, that does not seem to help with the problem I am facing. I am clearly missing some information to reset this path.

**Comment by btekin** [comment]
Hi Niveditha, thanks for pointing out this, this error was fixed before for single object pose estimation part, but for the multi-object pose estimation part, there were still hardcoded path names in `train_occlusion.txt`. Now I have updated the repo to fix this issue. Please let me know if the error persists.

**Comment by nkalavak** [comment]
I updated the path and am able to train as well. Thanks for acting on this swiftly.
