### ISSUE TITLE
wrong reshape

### ISSUE THREAD

**Issue by simama** [Microsoft/singleshotpose#32]
https://github.com/Microsoft/singleshotpose/blob/1e6bfae97ee8e307abd3d06bf062b33f5d713af4/multi_obj_pose_estimation/valid_multi.py#L106
this seems to be wrong reshaping. Your `read_truths_args` in `utils.py` returns shape (-1, 19), which you flatten to len 1050, and then reshape back with above line. In case when you have more targets this will not work properly.

**Comment by btekin** [comment]
Indeed if there are more targets in the label file, this will not work properly. However, when we test for multiple objects, we give the target objects individually in separate files during validation (note that `read_truths_args` is only used during validation). Therefore, in the current form, during validation this doesn't cause any problems. However, if one wants to give all the test targets in one label file, s/he would need to modify this part of the code accordingly.
