### ISSUE TITLE
Replacing the Calibration Data

### ISSUE THREAD

**Issue by eyildiz-ugoe** [Microsoft/singleshotpose#35]
As I am trying to reproduce the results with the same holepuncher (of LINEMOD) but with a different camera, I need to change the calibration matrix in the code, which is in the file named `utils.py`:

```
def get_camera_intrinsic():
    K = np.zeros((3, 3), dtype='float64')
    K[0, 0], K[0, 2] = 572.4114, 325.2611
    K[1, 1], K[1, 2] = 573.5704, 242.0489
    K[2, 2] = 1.
    return K
```

Normally, matrix K (intrinsic) should be composed of the following:

```
[fx, 0, 0]
[s, fy, 0]
[cx, cy, 1]
```
where:

```
[cx, cy] — Optical center (the principal point), in pixels.
(fx,fy) — Focal length in pixels. 
s — Skew coefficient, which is non-zero if the image axes are not perpendicular.
```

Given that, what is the structure of the K matrix in the code? Since it has slightly different construction as such:

```
>>> K
array([[572.4114,   0.    , 325.2611],
       [  0.    , 573.5704, 242.0489],
       [  0.    ,   0.    ,   1.    ]]) 
```

I need to know which element is what since I will replace the values with my own intrinsic values.

**Comment by SergioRAgostinho** [comment]
> Normally, matrix K (intrinsic) should be composed of the following:
> 
> [fx, 0, 0]
> [s, fy, 0]
> [cx, cy, 1]
> 
> 

Not really. The usual intrinsics matrix is exactly the transpose of what you claim. https://en.wikipedia.org/wiki/Camera_resectioning#Intrinsic_parameters
```
[fx, s, cx]
[0, fy, cy]
[0, 0, 1]
```

Which is why this makes sense
```
>>> K
array([[572.4114,   0.    , 325.2611],
       [  0.    , 573.5704, 242.0489],
       [  0.    ,   0.    ,   1.    ]]) 
```

**Comment by eyildiz-ugoe** [comment]
For some reason MATLAB says otherwise: https://de.mathworks.com/help/vision/ug/camera-calibration.html

But alright, I'll then take this as K:

[fx, s, cx]
[0, fy, cy]
[0, 0, 1]

and replace the values accordingly. Thanks btw!
