### ISSUE TITLE
Other dataset

### ISSUE THREAD

**Issue by zhanghanduo** [Microsoft/singleshotpose#36]
The dataset you provided has mesh ply file containing vertex information. If I want to extract 3D proposals from KITTI or cityscape dataset, can I use the code?

**Comment by btekin** [comment]
In our approach, we use the ply files just to extract the corner points of the 3D bounding box surrounding the object, i.e. we do not use the full detailed mesh of the object. Therefore, in principle, if you would like to extract 3D proposals from these datasets, you can modify the part of the code where we read .ply files and directly get the 3D bounding box without processing the mesh first.

**Comment by jzheng84** [comment]
@btekin Hello, I am a little confused about the evaluation code. Why is the mesh necessary if there are already labels w/ the 3D bounding box coordinates? I currently have the labels but not the ply file, how can I properly remove the dependency on the ply? Do the 3D coordinates obtained from the mesh need to be in some specific orientation (object is facing forward)?

Thanks!
