### ISSUE TITLE
question about dataset

### ISSUE THREAD

**Issue by edisonchensy** [Microsoft/singleshotpose#38]
what does these values mean?  For example,

0 0.413748 0.375966 0.450491 0.435113 0.451697 0.337961 0.381431 0.435781 0.378852 0.337811 0.447729 0.390781 0.448722 0.297217 0.382641 0.391062 0.380281 0.296740 0.072845 0.139041

(in /singleshotpose/LINEMOD/ape/labels/)

can you please help me? thank you

**Comment by PeterZheFu** [comment]
The author has a section explaining the label files here: https://github.com/Microsoft/singleshotpose#label-files

**Comment by edisonchensy** [comment]
@PeterZheFu Thank you for pointing that, but how to i get those values : 

x0 (x-coordinate of the centroid), 3rd number: y0 (y-coordinate of the centroid), 4th number: x1 (x-coordinate of the first corner), 5th number: y1 (y-coordinate of the first corner), ..., 18th number: x8 (x-coordinate of the eighth corner), 19th number: y8 (y-coordinate of the eighth corner), 20th number: x range, 21st number: y range.

how to do the label on 2D images? Since I can only get 4 coordinates (2D bounding box) on 2D images.
How do I know the 3D bounding box coordinates on 2D images? please help me, thank you.

by the way, do you have qq or wechat or other app that i can discuss with you?

**Comment by btekin** [comment]
Please see: #37 

Closing this issue as similar threads are going on in #42, #37 and #14.
