### ISSUE TITLE
how to get the labels for own datasets (21 numbers)

### ISSUE THREAD

**Issue by edisonchensy** [Microsoft/singleshotpose#42]
@PeterZheFu @btekin 
I am still confused with this part, for the label file in LINEMOD, how to get the 18 coordinates? 

Currently, I got the Camera intrinsic, mesh models and  the dimension of the my object (Length, Width, Height), I intuitively set the object centroid to be (0,0,0), so I can also get the coordinates of the 8 corners. (For example, Coke Can: L= 6.2cm, W= 6.2cm, H= 10.2cm . If the centriod is (0,0,0), the corners should be P1=(3.1,3.1,5.1), P2=(3.1,3.1,-5.1)... so on  )  Is this intuitive method correct? 

If it is correct, How do I project these 8 points on the 2D image? By the way, How to set the x, y range? please give me a help, thank you very much.

**Comment by btekin** [comment]
Please see: https://github.com/Microsoft/singleshotpose/issues/37#issuecomment-422360436
