### ISSUE TITLE
what is diam in cfg file?

### ISSUE THREAD

**Issue by edisonchensy** [Microsoft/singleshotpose#43]
train  = LINEMOD/ape/train.txt
valid  = LINEMOD/ape/test.txt
backup = backup/ape
mesh = LINEMOD/ape/ape.ply
tr_range = LINEMOD/ape/training_range.txt
name = ape
diam = 0.103

for example, this diam = 0.103, that is the diam?

**Comment by btekin** [comment]
Please see #13 and refer to already closed issues before opening new ones.
