### ISSUE TITLE
About Label Files

### ISSUE THREAD

**Issue by SonOfCoding** [Microsoft/singleshotpose#46]
#37 
@btekin , @eyildiz-ugoe . Hi, you said we can project the 3D keypoints to 2D by using the compute_projection function you provided. However, do I have to change proj_2d_gt   = compute_projection(**corners3D**, Rt_gt, internal_calibration) instead of proj_2d_gt   = compute_projection(**Vertices**, Rt_gt, internal_calibration)? Because the label is 2D projection of the 3D 
eight corners. By the way, how to get the 2D projection of the object's centroid (0,0,0) ?  

Thank you

**Comment by lesleyhaha** [comment]
Did you solve this problem? I also have this question
