### ISSUE TITLE
RuntimeError: The size of tensor a (13) must match the size of tensor b (5408) at non-singleton dimension 3

### ISSUE THREAD

**Issue by edisonchensy** [Microsoft/singleshotpose#5]
I got this problem, when I want to train the model (python train.py cfg/ape.data cfg/yolo-pose.cfg backup/ape/init.weights), my environment: python 2.7.14 , cuda8.0, cudnn 5.1, pytorch 0.4.0. Could you please give me a help??? Thank you very much.

Traceback (most recent call last):
  File "train.py", line 397, in <module>
    niter = train(epoch)
  File "train.py", line 91, in train
    loss = region_loss(output, target)
  File "/home/edison/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data1/edison/singleshotpose/region_loss.py", line 205, in forward
    pred_corners[0]  = (x0.data + grid_x) / nW
RuntimeError: The size of tensor a (13) must match the size of tensor b (5408) at non-singleton dimension 3

**Comment by zx007zls** [comment]
You just need to use pytorch 0.3.1 instead of 0.4.0, and it will solve all of your problems.

**Comment by edisonchensy** [comment]
thanks

**Comment by banannakn** [comment]
Is there any other solution than just downgrading?? Otherwise PyTorch is not compatible with Python any longer.. (and downgrading Python is also not compatible with other stuff and so on)
