### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by SonOfCoding** [Microsoft/singleshotpose#50]
Hi, @btekin I try to train and test my own dataset. I only train and test one object, toy-bear.  However, After training, when I want to valid my object. I get this problem. Could you please help me? Thank you.

john@laptop:~/john/singleshotpose$ python valid.py cfg/bear_toy.data cfg/yolo-pose-pre.cfg backup/bear_toy/model_backup.weights

Traceback (most recent call last):
  File "valid.py", line 275, in <module>
    valid(datacfg, cfgfile, weightfile, outfile)
  File "valid.py", line 139, in valid
    all_boxes = get_region_boxes(output, conf_thresh, num_classes)
  File "/john/singleshotpose/utils.py", line 338, in get_region_boxes
    assert(output.size(1) == (19+num_classes)*anchor_dim)
AssertionError

I have print the value of  (output, conf_thresh, num_classes)

output:
(0 ,0 ,.,.) =
 -2.6282e-02 -1.1638e-01  3.1015e-02  ...   1.1922e-01  1.1074e-01  5.2097e-03
 -3.1200e-02 -1.2207e-01  6.0752e-02  ...   4.6943e-02  3.4072e-02  8.3957e-04
  1.1783e-01 -1.5114e-02  2.2526e-02  ...  -4.3052e-02 -1.4134e-02  8.0588e-03
                 ...                   ⋱                   ...
 -3.6536e-02 -9.4302e-02 -1.2103e-01  ...   6.7788e-03 -2.7891e-02 -2.3125e-02
  5.8908e-02 -2.4154e-02  1.8790e-02  ...  -3.0124e-02 -3.6338e-02 -9.2290e-02
  4.6499e-03  3.7421e-02  6.2782e-02  ...  -6.0601e-02 -8.3703e-02 -4.8863e-02

(0 ,1 ,.,.) =
  3.7348e-02  8.0601e-02 -3.8682e-02  ...  -7.8329e-02 -1.2706e-01 -6.6510e-02
 -1.0373e-01  6.7127e-02  6.3087e-02  ...   4.4907e-02 -2.6325e-02 -5.6617e-02
 -1.2971e-01 -1.4979e-01 -5.8169e-02  ...  -4.4630e-02 -1.5308e-01 -5.1643e-02
                 ...                   ⋱                   ...
 -1.4815e-01 -1.3714e-01 -1.5018e-01  ...  -1.1391e-01 -2.0022e-01 -4.1368e-02
 -1.6764e-01 -1.2512e-01 -1.2874e-01  ...  -1.3810e-01 -1.0333e-01 -1.0093e-01
 -1.5435e-01 -1.9643e-01 -1.6086e-01  ...  -1.5192e-01 -1.5799e-01 -1.1227e-01

(0 ,2 ,.,.) =
  5.4995e-02  5.9248e-03 -2.5956e-02  ...   1.0725e-02  1.7036e-02 -5.8850e-02
 -7.3472e-03  5.0274e-02 -6.4523e-02  ...  -2.2691e-02  6.2444e-03 -3.6810e-02
  1.9026e-01  5.2537e-02 -1.3431e-01  ...  -1.1706e-01 -6.8829e-02 -7.9105e-02
                 ...                   ⋱                   ...
  2.5623e-02  2.2308e-02 -2.5726e-02  ...   6.3350e-02  5.5525e-02  2.5616e-02
  9.1978e-02 -3.2332e-02 -3.5101e-02  ...   1.7200e-02 -1.2062e-02  4.8496e-03
 -3.6505e-02  2.4037e-03 -6.2010e-02  ...  -1.2425e-02 -2.2164e-02 -4.8250e-02
   ...

(0 ,29,.,.) =
 -2.7069e-02 -1.6055e-02  1.1301e-01  ...  -1.2177e-03 -1.2537e-01 -6.5511e-02
  1.3091e-01 -1.8412e-02 -1.1215e-01  ...   6.4691e-03 -5.1697e-02 -7.6036e-02
  7.9545e-02 -4.6112e-02 -1.7834e-01  ...  -6.0202e-02 -7.8994e-02 -1.2372e-01
                 ...                   ⋱                   ...
 -6.9567e-02 -7.1485e-02 -1.7435e-02  ...  -7.7636e-02 -4.5202e-02 -7.5089e-02
 -4.6567e-02 -6.2728e-02 -1.2260e-01  ...  -4.8473e-02 -9.4372e-02 -7.8866e-02
 -4.5883e-02 -9.8076e-02 -7.5239e-02  ...  -1.1135e-01 -5.4546e-02 -9.3099e-02

(0 ,30,.,.) =
 -9.6636e-02 -1.0497e-01 -7.5623e-02  ...  -2.4792e-02 -8.5384e-02 -1.0472e-01
 -1.0639e-01 -5.6438e-02  2.2714e-03  ...   1.6224e-02  9.1031e-03 -8.7191e-02
 -2.1391e-01  2.7976e-02 -1.3651e-02  ...   3.0248e-02 -4.5505e-02 -1.2442e-01
                 ...                   ⋱                   ...
 -1.6899e-01 -7.7362e-03 -3.5663e-02  ...  -1.1511e-01 -1.3709e-01 -1.4391e-01
 -1.0154e-01 -5.0749e-02 -2.1263e-02  ...  -1.2721e-01 -9.8940e-02 -1.3418e-01
 -1.5037e-01 -6.7391e-02 -5.3581e-02  ...  -1.5120e-01 -1.7679e-01 -1.8124e-01

(0 ,31,.,.) =
 -1.5346e-01 -1.3244e-01 -2.4529e-01  ...  -1.0987e-01 -5.2348e-02 -2.3235e-02
 -2.1193e-01 -3.1680e-01 -3.1731e-01  ...  -2.5150e-03 -1.0657e-01 -7.3463e-02
 -2.1910e-01 -4.3107e-01 -4.4805e-01  ...  -1.1789e-02  2.2698e-02 -1.2666e-01
                 ...                   ⋱                   ...
 -8.0657e-03 -4.5893e-02 -4.8971e-02  ...  -1.9136e-04 -3.9249e-02 -1.1822e-01
 -3.3907e-03 -3.4883e-02 -4.4246e-02  ...   4.3262e-02  3.0650e-02 -8.7762e-02
 -5.0029e-02 -8.6026e-02 -6.3097e-02  ...  -2.8686e-02 -1.4475e-02 -9.8525e-02
[torch.cuda.FloatTensor of size 1x32x17x17 (GPU 0)]

conf_thresh:
0.1

num_classes:
1

**Comment by SonOfCoding** [comment]
Also, I have printed some values in def get_region_boxes(output, conf_thresh, num_classes, only_objectness=1, validation=False):

output.size : <built-in method size of torch.cuda.FloatTensor object at 0x7f41adbe9fc8>
output.dim() : 4
output.size(0) : 1
output.size(1): 32

**Comment by btekin** [comment]
In cfg/yolo-pose.cfg you should set the number of filters in your last layer to (num_coords + num_classes + 1 conf value) * num_anchors. For example, if you have 1 class and 1 anchor box, the number of filters at the last layer should be equal to 20 instead of 32. This seems to be the reason why you are getting an assertion error. I have added a comment in cfg/yolo-pose.cfg that explains how to set the number of filters at the last layer for a custom dataset.
