### ISSUE TITLE
something for multi-gpu training

### ISSUE THREAD

**Issue by T-mac93** [Microsoft/singleshotpose#52]
hi, it's a amazing work . But I got some trouble when I use a big batch size for multi-gpu training. I changed the gpus = '0,1,2,3' , but the memory can only used in the first gpu. So i got the OUT OF MEMORY ERROR. can anyone give me some advise for multi gpu training? thx

**Comment by btekin** [comment]
About the out-of-memory error, make sure you have enough space in your GPU by freeing memory. You could also reduce the batch size to fit in to the GPU space. See #12 and #26  for additional discussions on how to resolve out-of-memory errors.

PyTorch DataParallel sets one GPU to gather and store all output, therefore the one GPU uses more memory than others. For a more balanced memory usage across multiple GPUs, please see the following discussion that also includes a potential solution: https://discuss.pytorch.org/t/dataparallel-imbalanced-memory-usage/22551
