### ISSUE TITLE
Disable multi-scale feature in training

### ISSUE THREAD

**Issue by nmoutinho** [Microsoft/singleshotpose#53]
Hi, I saw in [#26](https://github.com/Microsoft/singleshotpose/issues/26) that you are randomly changing the input resolution during training. How can I limit or disable this feature? Thanks.

**Comment by btekin** [comment]
Hi, you could comment out or modify the [this part](https://github.com/Microsoft/singleshotpose/blob/master/dataset.py#L40:L64) of the code to disable or limit this feature.
