### ISSUE TITLE
custom dataset with different image size and ply unit in mm

### ISSUE THREAD

**Issue by xkevincode** [Microsoft/singleshotpose#54]
Hi, I custom my own dataset with image 160*120 and I change code from 640*480 to 160*120. But i have some doubts.
1. What is the test_width and test_height = 672 in train.py and test_width and test_height = 544 in valid.py ?
2. My ply file is in mm while the LINEMOD ply file seems to be in meters, so I change the units of vertices  by dividing 1000, after training it seems to be ok, but when I run valid.py (also change vertex by dividing 1000) the result bbx is too large, if I do not divide, it seems to be correct. All the training accuracy is not very high after 400 epochs.
![figure_1-4](https://user-images.githubusercontent.com/22719841/49572035-d67ff500-f975-11e8-878c-6340670a3622.png)

**Comment by btekin** [comment]
1. We adopt a multi-scale training procedure and change the input resolution during training randomly. This allows us to be able to change the input resolution at test-time and predict from images with higher resolution. Therefore, the choice for the test resolution is not fixed to a single number and could be chosen arbitrarily from the multiples of the cell size (32 pixels). We arbitrarily chose 672 during validation at train.py and 544 for validation at valid.py. We provide an analysis on the effect of test resolution on the accuracy and the runtime in Table 7 of our paper. You could change this number according to which input resolution you would like to use for testing.

2. Which parts of the code did you change to work with your custom input resolution? You should make sure to change the default resolution values in respective functions (e.g. https://github.com/Microsoft/singleshotpose/blob/master/utils.py#L230) or specify them while calling these function. As a sanity check, could you train your model by first resizing the original image to 640x480?

**Comment by AimijiaTech** [comment]
> Hi, I custom my own dataset with image 160_120 and I change code from 640_480 to 160*120. But i have some doubts.
> 
> 1. What is the test_width and test_height = 672 in train.py and test_width and test_height = 544 in valid.py ?
> 2. My ply file is in mm while the LINEMOD ply file seems to be in meters, so I change the units of vertices  by dividing 1000, after training it seems to be ok, but when I run valid.py (also change vertex by dividing 1000) the result bbx is too large, if I do not divide, it seems to be correct. All the training accuracy is not very high after 400 epochs.
>    ![figure_1-4](https://user-images.githubusercontent.com/22719841/49572035-d67ff500-f975-11e8-878c-6340670a3622.png)

hello，can you tell me how you get the ply file of the object like linemod dataset？？？

**Comment by btekin** [comment]
Please refer to the first bullet point in the following link: https://github.com/Microsoft/singleshotpose/blob/master/label_file_creation.md

**Comment by saadhana** [comment]
@btekin 

>     2\. Which parts of the code did you change to work with your custom input resolution? You should make sure to change the default resolution values in respective functions (e.g. https://github.com/Microsoft/singleshotpose/blob/master/utils.py#L230) or specify them while calling these functions. As a sanity check, could you train your model by first resizing the original image to 640x480?


Is changing the code [here](https://github.com/Microsoft/singleshotpose/blob/master/utils.py#L230) necessary? As far as I understand, the function only calculates the confidences based on the differences between predicted and GT corners, which are both normalized. (Also, shouldn't the threshold change if we change the resolution?)

My dataset has images of multiple resolutions and the network works fine without these changes. I only had to load intrinsics differently for the PnP algorithm to work.

**Comment by btekin** [comment]
Thanks for your input! Indeed as long as you load intrinsics differently, changing the code in the above mentioned line should not be necessary. 

> Also, shouldn't the threshold change if we change the resolution?

Here, the normalized predicted and GT corners are scaled back to a predefined resolution and the specified threshold is also with respect to (in proportion to) that resolution. So, it wouldn't be necessary to change the the threshold for this specific reason. However, it is also true that some other threshold values might work better for different datasets/images.
