### ISSUE TITLE
Handling multiple objects per class

### ISSUE THREAD

**Issue by iamstg** [Microsoft/singleshotpose#56]
Does the code for multi-object pose estimation handle more than one object per class?

**Comment by btekin** [comment]
In its current form, we choose the output with the highest confidence as our prediction. If you instead use a sensible threshold and choose the outputs above that threshold, it should be able to handle more than one object per class.

**Comment by iamstg** [comment]
Thanks a lot.

**Comment by saadhana** [comment]
If we have multiple ground truth labels per image, the evaluation might not be correct. 

[Here](https://github.com/Microsoft/singleshotpose/blob/be52417f091c9226d9c6b525b13997a95ba16434/train.py#L187) we compare each ground truth bounding box with only one predicted box with the highest confidence score.
