### ISSUE TITLE
Question regarding division into S * S grid

### ISSUE THREAD

**Issue by iamstg** [Microsoft/singleshotpose#57]
First of all, thanks for the great work!
I had some questions regarding the implementation. As I correctly understand, a (9 * 2 + 1 + C) vector
is returned for each S * S grid where S is set to 13 to be same as YOLOv2 network. Where and how is this information regarding 'S' coded exactly?

As far as I tried to understand from the code, I could not find anything explicit to divide the image region into S * S grid. Does that S * S grid division come implicitly from the network architecture and the width and height of the RGB images in the initial layer and is reflected in the output dimensions S * S * D ? If it is so, how can we say for sure, that the network is dividing it that way, or if the S * S division is uniform ?
Also, in that case, if we change the output dimension to some other value say 7 * 7 * (9 * 2 + 1 + C), then would the network behave as if the images were divided into 7 * 7 grid?

**Comment by saadhana** [comment]
The image is always divided into cells of size 32*32 pixels. So we use image-sizes that are multiples of 32. The number of such cells depends on the input size. For training, images with multiple sizes are used. The output dimensions are S * S * D, but S may be different for each batch. 

Checkout [this](https://github.com/Microsoft/singleshotpose/blob/be52417f091c9226d9c6b525b13997a95ba16434/dataset.py#L40) line in dataset.py. 

If the input image size is 416*416, S = 13
if the input image size is 672*672, S = 21

**Comment by btekin** [comment]
Thanks for your explanation @saadhana.
