### ISSUE TITLE
Minimum batch size and GPU

### ISSUE THREAD

**Issue by juanmed** [Microsoft/singleshotpose#62]
Hello,

I was wondering what is the minimum batch size and GPU that could be used for training. I have an nVidia GTX1050 gpu, with which I was able to train YOLOv3 using batch = 64 and subdivisions = 64. However for singleshotpose I need to reduce to batch = 4 and subdivisions = 4 to get to epoch 54.   If I  used batch = 8 and subdivisions = 8 in yolo-pose.cfg file, and number of workers in utils.py equal to 0 as suggested by previous issues, I cannot go beyond epoch 17. 

Using batch, subdivisions = 4, the GPU is almost 100% used (4017MB / 4037MB) when running `nvidia-smi -i 0 -q -d MEMORY`, and I made sure no other processes using CPU are running. 

My question is regarding minimum batch size and GPU for training. I know that if I had a better GPU training could be faster. 

My system settings are:
Ubuntu 16.04LTS
Nvidia GeForce GTX 1050 Ti/PCIe/SSE2
Intel® Core™ i5-8400 CPU @ 2.80GHz × 6 
Cuda 8.0, Pytorch 0.3.1, Python2.7
System RAM: 8.7GB

Thanks for your answer.

**Comment by btekin** [comment]
I haven't done a full analysis on this, but I have run this code and a few different variants of it on Pascal Titan X, Tesla M40 and GTX 1070. Among them, the one with the least memory size is GTX 1070 with 8 GB. If I remember correctly, I could still use a batch size of 16 with 8 subdivisions on this GPU. In any case, the method seems robust against different number of batch sizes and lowering the batch size would allow to train the code on GPUs with low memory sizes (although at the cost of longer training times).

**Comment by juanmed** [comment]
Thanks for your insight. I did tried on several other GPUs and the max batch was 16 with 8 subdivisions, but this was on a p3.2xlarge instance at Amazon aws. I thought I could work with batch=32 but was not possible. My dataset was 25k however. Closing this issue.
