### ISSUE TITLE
Small example and "get_region_boxes" slowest computation time

### ISSUE THREAD

**Issue by juanmed** [Microsoft/singleshotpose#63]
Hello,

For anyone interested I made a small script that takes as input an input image (together with cfg and weight files) and outputs a bounding cube over the detected object. You can find it in [my fork](https://github.com/juanmed/singleshot6Dpose) with name test1.py. I did it based on what valid.py does. Please do note that I have never used Pytorch before so any comments from improvement are more than welcome.

I had another question however. While getting computation times, I got the following results:
Inference time (forward pass): 10-13ms
get_region_boxes method time: **43-45ms**!!
PnP solving: 0.55-0.58ms 
Total computation time: 53.55 - 58.58ms (much slower than inference time!)

The inference time is very fast, but the whole computation time (from sending image to network to 6DoF estimatate computation) is slow, around 55ms, which is 5x times the inference time of the network! And the bottleneck is the "get_region_boxes" method in utils.py. It takes 80% of the computation time!

Although this computation times will depend on system setting, is this result to be expected? Is get_region_boxes method really 4x slower than the network prediction? I have not finished analyzing this part of the code, however I want to confirm this is the result the author and other people get. Are there any comments on how to speed it up so that it takes >5% of the time?

My system settings for this test are (I am using python3, pytorch0.4 compatible version on btekin/singleshot6Dpose repository):
Ubuntu 16.04LTS
Nvidia GeForce GTX 1050 Ti/PCIe/SSE2
Intel® Core™ i5-8400 CPU @ 2.80GHz × 6
Cuda 8.0, Pytorch 0.4.0, Python3.5
System RAM: 8.7GB

**Comment by btekin** [comment]
Hi @juanmed, I agree I think the whole runtime could even be made faster by optimizing get_region_boxes. For example for single object pose estimation (by assuming a known single object in the scene), you could just use the highest confidence prediction. I also think that some loops could be vectorized for further speed-up.

**Comment by juanmed** [comment]
Thanks you for your input @btekin. I will try to implement this improvements in my fork. I will close this issue for now.
