### ISSUE TITLE
Predicting 4 points instead of 9?

### ISSUE THREAD

**Issue by anuar12** [Microsoft/singleshotpose#64]
Hello,

Thank you for open-sourcing your code!

I wanted to predict only 4 points in 2D (or 5 if I want the center too) instead of 9 in multi-object setting. Would you mind telling which parts of the code to modify? Are there any conceptual hints you can give for me to understand the whole process (I am familiar with YOLO v2 detection on its own)?

What I need to change:
1) strip off bunch of lines that contain `tx` and `x, y` in `region_loss_multi.py`, and also change the size of tensors (instead of 19 it would be 4*2+1=9) and etc...
2) Modify the code in `image_multi.py`
3) Modify `get_corresponding_region_boxes()` in `utils.py` to get bboxes at test-time.
3) change the `coords=18` to `coords=8` in cfg file.
4) For evaluation I am planning to use IOU and probably ADD (l1/l2 distance between points), so I will modify `eval()` in `train_multi.py`

Also if I wanted to predict variable number of keypoints (single keypoint objects and 4-keypoint objects at the same time), as I understand it wouldn't be simple because output tensor has to be of fixed size.

Cheers

**Comment by btekin** [comment]
Thanks for your interest in the code. The steps that you have written are all necessary. You should basically make sure to change all the hard-coded parts about the number of keypoints (there are a couple of them during evaluation and some in utils.py functions). If I get the time, I will try to also go over the code to modularize it to work with a custom number of keypoints.
