### ISSUE TITLE
Getting 0 accuracy on customized dataset

### ISSUE THREAD

**Issue by s0972456** [Microsoft/singleshotpose#65]
I am getting zero accuracies on all metrics during training and the validation phase. The commends I run were:
python train.py cfg/expo-eraser.data  cfg/yolo-pose-pre.cfg cfg/darknet19_448.conv.23
cp backup/expo-eraser/model.weights backup/expo-eraser/init.weights
python valid.py cfg/expo-eraser.data cfg/yolo-pose.cfg backup/expo-eraser/model_backup.weights

Like the name of the dataset suggests, I was not testing on an item that would be difficult for the algorithm.
The error sounds most likely a scale issue, but the mesh I created is indeed in meter. I also acquired the mesh myself, and I am very certain about the correctness of the RT transformations and the 2D projections.

I do have 2 things unclear though:
1.  I normalized all 2D pixels and range, e.g. if the center of the object is (340,240)  on a 640*480 image, the value I provided in the label file is 0.5 0.5, is this the right practice?
2. About the 8 corners of the 3D bounding box, while the axis aligned bounding box on the ground truth pose frame satisfies  [[min_x, min_y, min_z], [min_x, min_y, max_z], [min_x, max_y, min_z], [min_x, max_y, max_z], [max_x, min_y, min_z], [max_x, min_y, max_z], [max_x, max_y, min_z], [max_x, max_y, max_z]], this is not satisfied anymore as the corners will get transformed with the subsequent frames?

**Comment by jgcbrouns** [comment]
Did you manage to solve the problem? I am also getting 0% accuracy as it seems: 
`019-03-20 14:12:14    Number of test samples: 60
-----------------------------------
  tensor to cuda : 0.000999
         predict : 0.011994
get_region_boxes : 0.015990
            eval : 0.035156
           total : 0.064140
-----------------------------------
2019-03-20 14:12:20    Mean corner error is 355.253784
2019-03-20 14:12:20    Acc using 5 px 2D Projection = 0.00%
2019-03-20 14:12:20    Acc using 0.0103 vx 3D Transformation = 0.00%
2019-03-20 14:12:20    Acc using 5 cm 5 degree metric = 0.00%
2019-03-20 14:12:20    Translation error: 18381.882744, angle error: 125.722093`

**Comment by s0972456** [comment]
Nope, I checked all my labeling and couldn't find what is not correct.

> Did you manage to solve the problem? I am also getting 0% accuracy as it seems:
> 
> 019-03-20 14:12:14 Number of test samples: 60
> tensor to cuda : 0.000999
> predict : 0.011994
> get_region_boxes : 0.015990
> eval : 0.035156
> total : 0.064140
> 2019-03-20 14:12:20 Mean corner error is 355.253784
> 2019-03-20 14:12:20 Acc using 5 px 2D Projection = 0.00%
> 2019-03-20 14:12:20 Acc using 0.0103 vx 3D Transformation = 0.00%
> 2019-03-20 14:12:20 Acc using 5 cm 5 degree metric = 0.00%
> 2019-03-20 14:12:20 Translation error: 18381.882744, angle error: 125.722093

**Comment by btekin** [comment]
#83 closing the duplicate.

**Comment by G-YY** [comment]
> Did you manage to solve the problem? I am also getting 0% accuracy as it seems:
> 
> 019-03-20 14:12:14 Number of test samples: 60
> tensor to cuda : 0.000999
> predict : 0.011994
> get_region_boxes : 0.015990
> eval : 0.035156
> total : 0.064140
> 2019-03-20 14:12:20 Mean corner error is 355.253784
> 2019-03-20 14:12:20 Acc using 5 px 2D Projection = 0.00%
> 2019-03-20 14:12:20 Acc using 0.0103 vx 3D Transformation = 0.00%
> 2019-03-20 14:12:20 Acc using 5 cm 5 degree metric = 0.00%
> 2019-03-20 14:12:20 Translation error: 18381.882744, angle error: 125.722093

How did you solve the problem?I have met the same problem.Thank you! 
@F2Wang
