### ISSUE TITLE
Multi-object pose estimation on custom dataset

### ISSUE THREAD

**Issue by nmoutinho** [Microsoft/singleshotpose#67]
Hi, I would like to train this network for multi-object pose estimation on a custom dataset containing almost 100 different objects (without any of the OCCLUSION objects). How can I adapt the current multi-train code to allow the training of new objects? I've already trained this network for a single custom object but it seems the multi-object training functions are not so well prepared for custom data. 

Thank you for your help ;)
Best, Nuno

**Comment by Abdul-Mukit** [comment]
Hi @nmoutinho , I just studied the multi-object pose training codes. It looks like the training images are not pre-stored rather they are generated on the fly. Am I right?
I was super impressed by that idea. Amazing.
BTW, how did you manage to train for multiple objects at the end? Did you use the single-object codes but modified the yolo-pose.cfg file to account for two classes instead of one? I am working on this problem too, so would appreciate if you could share some information.

**Comment by nmoutinho** [comment]
Hi @Abdul-Mukit, I ended up adapting the "multi_obj_pose_estimation" code to allow for a custom multi-object dataset. Unfortunately, it required a lot more than just changing the .cfg file, since the rep code was highly dependant on the dataset they were using.

**Comment by Abdul-Mukit** [comment]
@nmoutinho , Thank you for your reply. Yes I realized that yesterday. Going to do the same thing next. Before starting wanted to check with you if my understanding was correct. Thanks for the information.

**Comment by mimi616888** [comment]
hello, I want to use two classes of my custom dataset to training the multiple objects model.
However, I met this problem when compile the "train_multi.py"
Traceback (most recent call last):
File "train_multi.py", line 413, in
niter = train(epoch)
File "train_multi.py", line 87, in train
loss = region_loss(output, target, epoch)
File "/home/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in call
result = self.forward(input, **kwargs)
File "/media/DATA/YOLO6D/multi_obj_pose_estimation/region_loss_multi.py", line 122, in forward
output = output.view(nB, nA, (2self.num_keypoints+1+nC), nH, nW)
RuntimeError: shape '[32, 5, 21, 13, 13]' is invalid for input of size 865280

Is there anyone can assist me? Thank you first!

**Comment by xiaoxiongmaoxuexi** [comment]
@mimi616888  Hello, I have the same problem as you. I don't know how to configure yolo-pose-multi.cfg, have you solved this problem?

**Comment by kisidid** [comment]
@xiaoxiongmaoxuexi Modify the filters values in line 235 of yolo-pose-multi.cfg. (2*9+1+(number of classes))*(number of anchors. default 5). If the number of classes is 2, filters=105.

**Comment by xiaoxiongmaoxuexi** [comment]
@kisidid   Thank you very much for your answer. When I modify number of classes is 2 according to your idea. I have encountered the following problems. Can you tell me how to modify them. Thank you again for your answer.
Traceback (most recent call last):
  File "/home/zhanggan/singleshotpose-master/multi_obj_pose_estimation/train_multi.py", line 458, in <module>
    niter = train(epoch)
  File "/home/zhanggan/singleshotpose-master/multi_obj_pose_estimation/train_multi.py", line 87, in train
    loss = region_loss(output, target, epoch)
  File "/home/zhanggan/anaconda3/envs/singleshotpose1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhanggan/singleshotpose-master/multi_obj_pose_estimation/region_loss_multi.py", line 188, in forward
    print('%d: nGT %d, recall %d, proposals %d, loss: x %f, y %f, conf %f, cls %f, total %f' % (self.seen, nGT, nCorrect, nProposals, loss_x.item(), loss_y.item(), loss_conf.item(), loss_cls.item(), loss.item()))
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by kisidid** [comment]
@xiaoxiongmaoxuexi
I had the same problem. An error occurred when the label's class index did not start at zero. Why don't we check the label?
