### ISSUE TITLE
how to create mask image

### ISSUE THREAD

**Issue by flowtcw** [Microsoft/singleshotpose#70]
excuse me， I have a question about how to generate mask image on my custom ply model which just like you create in LineMod.
thanks!

**Comment by btekin** [comment]
For the LINEMOD dataset, full 3D CAD models and the ground-truth pose of the object is provided. To get segmentation masks, you could project the 3D CAD model onto the image with the provided ground-truth pose and assign to the projected pixel values 1, while leaving other pixel values as 0.
