### ISSUE TITLE
backup.tar link is broken

### ISSUE THREAD

**Issue by joefriel** [Microsoft/singleshotpose#74]
The link to backup.tar is not working. 

This link:
https://onedrive.live.com/download?cid=0C78B7DE6C569D7B&resid=C78B7DE6C569D7B%21191&authkey=AP183o4PlczZR78

results in this:

"This item might not exist or is no longer available
This item might have been deleted, expired, or you might not have permission to view it. Contact the owner of this item for more information."

**Comment by joefriel** [comment]
Looks like it is now working

**Comment by Yanhui-He** [comment]
It's not working! I cannot download the file.

 This link:
https://onedrive.live.com/download?cid=0C78B7DE6C569D7B&resid=C78B7DE6C569D7B%21191&authkey=AP183o4PlczZR78

**Comment by Yanhui-He** [comment]
@btekin 

Hello, this link is broken when the download is not complete.
https://onedrive.live.com/download?cid=0C78B7DE6C569D7B&resid=C78B7DE6C569D7B%21191&authkey=AP183o4PlczZR78

I have tried it many times, but there is still no way to download the file (backup.tar).
