### ISSUE TITLE
PnP fails with right coordinate points

### ISSUE THREAD

**Issue by saadhana** [microsoft/singleshotpose#84]
The trained network produces correct keypoints, but the PnP algorithm gives very incorrect poses. For example, depth values of zero or very large negative numbers. 

I visualized and verified the 2D coordinates predicted are correct. Also, the error doesn't happen with all predictions. Sometimes within the same image, there are correct and incorrect poses. 

The object is a thin cuboid, 8x8x2 cm. I tried to change to solvePnPRansac() as in [this](https://github.com/Microsoft/singleshotpose/blob/766d5eced25df6f0c438c6414c07b8b686c0558e/utils.py#L101) line. There are now fewer incorrect poses but it didn't solve the problem completely. 

Are there any other alternatives to correctly match 2D-3D correspondences?

**Comment by btekin** [comment]
Thanks for your feedback. I wonder if this is related to the opencv version you are using. Did you have this problem earlier as well? Which version of opencv are you using? I am currently traveling but will look into this as soon as possible.

**Comment by btekin** [comment]
For reference, my opencv version is 3.4.3 and pnp provides accurate results on LINEMOD using this version.

**Comment by saadhana** [comment]
Thanks for the reply @btekin.

I still get the same results when I use opencv version 3.4.3.
Also, the results were accurate for some other objects that I tested using the same algorithm. I was wondering if this has something to do with the algorithm itself.  

The object for which PnP fails has a size of 8x8x2 cm.  
 For example,

```
points3d = [[ 0.        ,  0.        ,  0.        ],
   ....:        [-0.0860909 , -0.050275  , -0.03634   ],
   ....:        [-0.0860909 , -0.050275  ,  0.0042    ],
   ....:        [-0.0860909 ,  0.050275  , -0.03634   ],
   ....:        [-0.0860909 ,  0.050275  ,  0.0042    ],
   ....:        [ 0.00720001, -0.050275  , -0.03634   ],
   ....:        [ 0.00720001, -0.050275  ,  0.0042    ],
   ....:        [ 0.00720001,  0.050275  , -0.03634   ],
   ....:        [ 0.00720001,  0.050275  ,  0.0042    ]]

points2d = [[ 955.289  ,  420.2667 ],
   ....:        [ 919.0348 ,  363.02173],
   ....:        [ 948.9853 ,  328.90167],
   ....:        [ 879.16986,  423.60797],
   ....:        [ 905.62866,  389.72952],
   ....:        [1003.7523 ,  447.08157],
   ....:        [1031.7747 ,  413.8837 ],
   ....:        [ 959.3554 ,  502.82587],
   ....:        [ 983.0211 ,  469.66736]]

cameraMatrix = [[1.0790131e+03, 0.0000000e+00, 6.4000000e+02],
   ...:        [0.0000000e+00, 1.0790131e+03, 4.8000000e+02],
   ...:        [0.0000000e+00, 0.0000000e+00, 1.0000000e+00]]
```
`pnp(points3d, points2d, cameraMatrix)`
results in a translation of `[  9.04003410e-05, 4.37270641e-02, 4.40896472e-02]` if 'solvePnP' is used in the pnp method. 

The same inputs result in a translation of `[2.931641604603839046e-01, -3.187160154882406199e-02, 8.774756454979734110e-01]` if 'solvePnPRansac' is used.

Sometimes both methods provide incorrect values.  

Though 'solvePnPRansac' works in most cases, I was curious to know why it doesn't work sometimes.

**Comment by btekin** [comment]
Is your object a symmetric object? If it is the case, the 2D keypoint predictions might seem accurate but in fact they might there might be left/right ambiguity in the predictions. 

In LineMod there is a similar thin object, e.g. glue but the accuracy is reasonably good in that case. 

SolvePnPRansac could indeed be powerful in the case of predictions with outliers. In that case, using more keypoints could also prove useful.

**Comment by saadhana** [comment]
Yes, my object is kinda symmetric. 
I am already working on training with additional keypoints. Will let you know if it is successful.

**Comment by Hao-HUST** [comment]
Hi, all. Did you solve the problem? My model is symmetric also, and the predicted keypoints are almost the same with GT, but the PnP result is completely reversed in three axes.
