### ISSUE TITLE
Exact custom inputs yet zero accuracy while training

### ISSUE THREAD

**Issue by MohamadJaber1** [Microsoft/singleshotpose#85]
Firslty, I would like to thank you for this work. And also a big thanks for @Juanmed for his amazing fork where it saved me a lot of time for labelling. And I saw that he has _test.py_ file which I am looking forward to test my new images later in a robotic simulation environment and  get the 6D pose. **But with the results I am getting so far, I am wondering how can I proceed**.

**My _.data_ file is meeting all the exact requirements. I don't know whats the problem with learning it with _singleshotpose_?**
Before I raised this issue, I almost went through all the issues (opened and closed ones). I am using, PyTorch 0.4.1 with Python 3.7, CUDA 9.0, cuDNN 7. I forked @btekin work, as it is said to be compatible with Python 3 and PyTorch 0.4. My GPU is NVIDIA Quadro K2200 4 GB memory.  
 
I am running the following line at cmd (._cfg_ file changed to batch size = 4 and subdivision = 4 as it was showing that CUDA is out of memory). I have changed the _utils.py_ to match my camera intrinsic.
`python train.py cfg/lego.data cfg/yolo-pose-pre.cfg cfg/darknet19_448.conv.23 cp  backup/benchvise/init.weights` 
![SSp_V2_1](https://user-images.githubusercontent.com/48984186/56209781-a1d32700-6054-11e9-90b5-5df5764892de.JPG)

And what I can observe is that the _model.weights_ file is **just created once** after first 10 epochs but **never updated** to the latest checkpoint. It means, the model is not improving at all. And after 177 epochs, the model got crashed with such an error. 

![SS6DP_error_2](https://user-images.githubusercontent.com/48984186/56264948-739f2700-60e8-11e9-9b46-15279158f23c.JPG)

**I will go through the exact steps I have followed to generate my own dataset. I know many issues have been opened just for this question. I am sure that these steps will be of huge help to other users :).** 

1. Generated **images** from Nvidia Deep Learning Data Synthesizer NDDS (Unreal engine project). I had  **1170 RGB images**, **1170 masked images** and their **3D bounding boxes**. I had also the **camera intrinsic parameters**.
![NDDS_SSP_3](https://user-images.githubusercontent.com/48984186/56194939-3aa57a80-6034-11e9-9859-6f740efebdc4.JPG)

My object is a lego piece and below is the output of one image. This is 1 out 65 different oritentations of the lego piece..
![77_lego_red_2x4](https://user-images.githubusercontent.com/48984186/56195018-632d7480-6034-11e9-8b29-23fa7126ab79.png)

2. For my **CAD** model which is _.STEP_ file, I have imported it to the unreal engine project using datasmith plugin. Exported it as ._FBX_ and then from _Blender_, I imported the ._FBX_ file and exported it as ._PLY_. #68 

3. From @juanmed fork, **labelling** was done with a python file called _ndds_dataset_creator.py_. I have gave my _json_ and RGB images as input and got the corresponding label _txt_ files. And the _train.txt_ and _test.txt_. It generated 21 values as needed. It mapped points from the 3D bounding box to points in the 2D image.  I have initially kept the training/testing ratio as 15%/85% as in the paper but with zero accuracy and then swapped this ratio to 85%/15% respectively.
One picture of the labelling, which seems to be correct. 
![NDDS_SSP_4](https://user-images.githubusercontent.com/48984186/56195175-b56e9580-6034-11e9-90f3-fd8546b7748b.JPG)

4. To give an accuracte value of the **diameter** which is in the ._data_ file for my _PLY_ file, I ran the following code to check my object _diam_ of my own _PLY_ file which is already provided at _valid.py_ but left commented. I also compared it with ape.ply to see if my values are accuracte and indeed it was.
![PLY_1](https://user-images.githubusercontent.com/48984186/56195338-11391e80-6035-11e9-9004-e6f011b845d6.JPG)

**Comment by btekin** [comment]
As discussed in #75, the issue seems to stem from providing wrong labels for the bounding box coordinates. Closing this as this is also being discussed in #75. Please feel free to continue discussing this in #75
