### ISSUE TITLE
RuntimeError: The shape of the mask [169] at index 0 does not match the shape of the indexed tensor [1, 13, 13] at index 0

### ISSUE THREAD

**Issue by rmizero** [microsoft/singleshotpose#88]
Hi, I am training my dataset called carm. and I get the following error when I try to pretrain the model.

mizero@rmizero:~/singleshot6Dpose$ python3 train.py cfg/carm.data cfg/yolo-pose-pre.cfg cfg/darknet19_448.conv.23 
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32
    1 max          2 x 2 / 2   416 x 416 x  32   ->   208 x 208 x  32
    2 conv     64  3 x 3 / 1   208 x 208 x  32   ->   208 x 208 x  64
    3 max          2 x 2 / 2   208 x 208 x  64   ->   104 x 104 x  64
    4 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    5 conv     64  1 x 1 / 1   104 x 104 x 128   ->   104 x 104 x  64
    6 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    7 max          2 x 2 / 2   104 x 104 x 128   ->    52 x  52 x 128
    8 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
    9 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128
   10 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
   11 max          2 x 2 / 2    52 x  52 x 256   ->    26 x  26 x 256
   12 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   13 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   14 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   15 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   16 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   17 max          2 x 2 / 2    26 x  26 x 512   ->    13 x  13 x 512
   18 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   19 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   20 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   21 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   22 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   23 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   24 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   25 route  16
   26 conv     64  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x  64
   27 reorg              / 2    26 x  26 x  64   ->    13 x  13 x 256
   28 route  27 24
   29 conv   1024  3 x 3 / 1    13 x  13 x1280   ->    13 x  13 x1024
   30 conv     32  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x  32
   31 detection
2019-04-30 18:02:35 epoch 0, processed 0 samples, lr 0.000100
8: nGT 8, recall 0, proposals 1352, loss: x 25.323454, y 67.364174, conf 0.000000, total 92.687630
16: nGT 8, recall 0, proposals 1352, loss: x 36.422775, y 78.672920, conf 0.000000, total 115.095695
24: nGT 8, recall 0, proposals 1352, loss: x 30.851065, y 52.881462, conf 0.000000, total 83.732529
32: nGT 8, recall 1, proposals 1352, loss: x 19.461891, y 28.387510, conf 0.000000, total 47.849403
40: nGT 8, recall 1, proposals 1352, loss: x 14.837030, y 24.735384, conf 0.000000, total 39.572414
48: nGT 8, recall 1, proposals 1352, loss: x 17.712580, y 35.876320, conf 0.000000, total 53.588898
56: nGT 8, recall 1, proposals 1352, loss: x 20.949785, y 40.246918, conf 0.000000, total 61.196701
64: nGT 8, recall 0, proposals 1352, loss: x 15.559206, y 28.157074, conf 0.000000, total 43.716278
72: nGT 8, recall 6, proposals 1352, loss: x 6.305926, y 6.975615, conf 0.000000, total 13.281541
80: nGT 8, recall 2, proposals 1352, loss: x 13.551977, y 20.233635, conf 0.000000, total 33.785614
88: nGT 8, recall 4, proposals 1352, loss: x 9.658031, y 13.644951, conf 0.000000, total 23.302982
96: nGT 8, recall 1, proposals 1352, loss: x 10.384680, y 17.337152, conf 0.000000, total 27.721832
104: nGT 8, recall 5, proposals 1352, loss: x 11.573566, y 13.644823, conf 0.000000, total 25.218390
112: nGT 8, recall 2, proposals 1352, loss: x 12.922074, y 12.597947, conf 0.000000, total 25.520021
120: nGT 8, recall 6, proposals 1352, loss: x 7.104557, y 10.567768, conf 0.000000, total 17.672325
128: nGT 8, recall 4, proposals 1352, loss: x 9.044456, y 28.682737, conf 0.000000, total 37.727192
136: nGT 8, recall 5, proposals 1352, loss: x 7.527264, y 7.952633, conf 0.000000, total 15.479897
Traceback (most recent call last):
  File "train.py", line 405, in <module>
    niter = train(epoch)
  File "train.py", line 94, in train
    loss = region_loss(output, target)
  File "/home/mizero/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mizero/singleshot6Dpose/region_loss.py", line 229, in forward
    build_targets(pred_corners, target.data, self.anchors, nA, nC, nH, nW, self.noobject_scale, self.object_scale, self.thresh, self.seen)
  File "/home/mizero/singleshot6Dpose/region_loss.py", line 67, in build_targets
    conf_mask[b][cur_confs>sil_thresh] = 0
RuntimeError: The shape of the mask [169] at index 0 does not match the shape of the indexed tensor [1, 13, 13] at index 0

**Comment by joefriel** [comment]
I think I hit that as well.  I replaced this line:

            cur_confs  = torch.max(cur_confs, corner_confidences9(cur_pred_corners, cur_gt_corners)) 

...with this line:

            cur_confs  = torch.max(cur_confs, corner_confidences9(cur_pred_corners, cur_gt_corners)).view_as(conf_mask[b]) 

...and I also added this line after the for loop:
        if (len(cur_confs.shape) == 1 ):
            cur_confs = torch.zeros(nAnchors).view_as(conf_mask[b])

(Note that the line after the for loop should be at the same indent level as the for statement on line 43)

I am not sure if this is the correct fix, but it worked for me.

**Comment by rmizero** [comment]
@joefriel thanks for responding to my issue. I did find a fix however. I changed to the python2 implementation, and it worked fine. Thx

**Comment by joefriel** [comment]
That makes sense, I am working in python3.  I guess you can close the issue?

**Comment by ubuntuyumiao** [comment]
> I think I hit that as well. I replaced this line:
> 
> ```
>         cur_confs  = torch.max(cur_confs, corner_confidences9(cur_pred_corners, cur_gt_corners)) 
> ```
> 
> ...with this line:
> 
> ```
>         cur_confs  = torch.max(cur_confs, corner_confidences9(cur_pred_corners, cur_gt_corners)).view_as(conf_mask[b]) 
> ```
> 
> ...and I also added this line after the for loop:
> if (len(cur_confs.shape) == 1 ):
> cur_confs = torch.zeros(nAnchors).view_as(conf_mask[b])
> 
> (Note that the line after the for loop should be at the same indent level as the for statement on line 43)
> 
> I am not sure if this is the correct fix, but it worked for me.

Hi, i met the same issue when i using RTX 2080 Ti to train my own dataset,but i try to midify the code as you describe, it does not work for me

**Comment by joefriel** [comment]
Are you using multi-object code (region_loss_multi.py)?

**Comment by mojoee** [comment]
I was training this algorithm on the KITTI Dataset and had the same issue when I started training. @joefriel thanks for the lines of code. It also worked for me. Just keep in mind that you have to add it before the line:   conf_mask[b][cur_confs>sil_thresh] = 0

**Comment by julingers** [comment]
I solved it as follows.
change https://github.com/microsoft/singleshotpose/blob/master/region_loss.py#L40 to the following code:
`conf_mask[b][(cur_confs>sil_thresh).view_as(conf_mask[b])] = 0`
Hope it helps you.
