### ISSUE TITLE
train multi_object without mask

### ISSUE THREAD

**Issue by SumeetBatra** [microsoft/singleshotpose#89]
Is there a simple way to train multi_object without using masks, because our dataset doesn't have any masks that we can use.

**Comment by btekin** [comment]
This would be possible, however using segmentation masks allow us to change the background of the image. We use this to be able to train the model with different backgrounds and increase the generalization ability of the approach in diverse backgrounds. So, you could, in principle, still train the network without it, but the generalization might not be as good.
