### ISSUE TITLE
label my own object but not in scene

### ISSUE THREAD

**Issue by SonOfCoding** [microsoft/singleshotpose#90]
for example, I have two objects, coke and pen. for the train or test dataset, if the image does not have coke, how do I label the .txt file for coke in that image? Can I label the object class and leave the rest of 20 number to become 0.00000?

**Comment by rmizero** [comment]
Are you working for multiple objects? in that case you should only use the images with both coke and pen visible. If for single object, then you should only put the 2d location of the target object. I hope it helps you

**Comment by btekin** [comment]
Yes, if the object is not visible in the image, it would not make sense to have labels for it, as it wouldn't be possible to estimate its 6D pose just by looking at the image.
