### ISSUE TITLE
dataset labellimg?

### ISSUE THREAD

**Issue by TDBTECHNO** [microsoft/singleshotpose#95]
I would like to ask that is there any labelling tool for your own custom dataset?I would like to use RGB camera. LIke for 2D images, we labell the images thhrough LabelImg, but what about 3D images or say bounding box?

**Comment by hlcool** [comment]
I think you could try [ObjectDatasetTools](https://github.com/F2Wang/ObjectDatasetTools)

**Comment by btekin** [comment]
Yes, the ObjectDatasetTools seem to be quite practical in generating your own dataset for pose estimation purposes. It also provides label files compatible with our dataset.

**Comment by Sciroccogti** [comment]
@btekin I wonder if there could be a wiki page? There have already been so many useful issues 😂, and I think simply offering some links to these issues will be quite helpful.
