### ISSUE TITLE
Question about the label change in data_augmentation 

### ISSUE THREAD

**Issue by ghoshaw** [microsoft/singleshotpose#98]
Hi, 
     I found that in the file image.py, the source  image is croped and the label change following it.  Then a resize op is used on image, but the label does not change.  Is this a bug or I misunderstand?

**Comment by justbin1123** [comment]
hey，I have the same question, did you understand it?

**Comment by ghoshaw** [comment]
Hi, 
    Because the label is normalized by the width and height of the image, so only the size changes does not effect the label. for example, a point (0.5, 0.5) in image of size (224, 224),   and (0.5, 0.5) in image of size(416, 416), the point is center for  these two image. so the label does not need to change.

**Comment by justbin1123** [comment]
thanks for ur reply！
